package org.jboss.ddoyle.drools.cep.demo;

import org.jboss.ddoyle.drools.cep.demo.model.SensorFact;

declare SensorFact
	@role( event )
	@timestamp( timestamp.getTime() )
	@expires( 2d )
end

rule "RainDetecting"
when
    $s1:SensorFact( rain > 0 ) from entry-point SensorStream
then
	System.out.println("Rain detected. Date: " +$s1.getTimestamp().getDate() + ", Time: " + $s1.getTimestamp().getTime());
end